CREATE CONSTRAINT event_ts IF NOT EXISTS
FOR (e:Event) REQUIRE e.timestamp IS UNIQUE;

CREATE CONSTRAINT entity_id IF NOT EXISTS
FOR (e:Entity) REQUIRE e.sysId IS UNIQUE;

CREATE CONSTRAINT station_id IF NOT EXISTS
FOR (s:Station) REQUIRE s.sysId IS UNIQUE;

CREATE CONSTRAINT entity_type IF NOT EXISTS
FOR (t:EntityType) REQUIRE t.name IS UNIQUE;

CREATE CONSTRAINT activity_name IF NOT EXISTS
FOR (a:Activity) REQUIRE a.name IS UNIQUE;